CREATE TABLE sys_dict_type (
  dict_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_name VARCHAR(100) DEFAULT '',
  dict_type VARCHAR(100) NOT NULL,
  status CHAR(1) DEFAULT '0',
  create_by VARCHAR(64) DEFAULT '',
  create_time TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
  update_by VARCHAR(64) DEFAULT '',
  update_time TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
  remark VARCHAR(500) DEFAULT ''
);
--;;
CREATE UNIQUE INDEX idx_sys_dict_type ON sys_dict_type(dict_type);
--;;
CREATE TABLE sys_dict_data (
  dict_code BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_sort INT DEFAULT 0,
  dict_label VARCHAR(100) DEFAULT '',
  dict_value VARCHAR(100) DEFAULT '',
  dict_type VARCHAR(100) NOT NULL,
  css_class VARCHAR(100) DEFAULT NULL,
  list_class VARCHAR(100) DEFAULT NULL,
  is_default CHAR(1) DEFAULT 'N',
  status CHAR(1) DEFAULT '0',
  create_by VARCHAR(64) DEFAULT '',
  create_time TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
  update_by VARCHAR(64) DEFAULT '',
  update_time TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
  remark VARCHAR(500) DEFAULT ''
);
--;;
CREATE INDEX idx_sys_dict_data_type ON sys_dict_data(dict_type);
--;;
CREATE INDEX idx_sys_dict_data_status ON sys_dict_data(status);
