CREATE TABLE sys_config (
  config_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_name VARCHAR(100) DEFAULT '',
  config_key VARCHAR(100) NOT NULL,
  config_value VARCHAR(500) DEFAULT '',
  config_type CHAR(1) DEFAULT 'N',
  create_by VARCHAR(64) DEFAULT '',
  create_time TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
  update_by VARCHAR(64) DEFAULT '',
  update_time TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
  remark VARCHAR(500) DEFAULT ''
);
--;;
CREATE UNIQUE INDEX idx_sys_config_key ON sys_config(config_key);
