-- 清空种子数据(两库通用;每条语句之间必须用 --;; 分隔)
DELETE FROM sys_user_role;
--;;
DELETE FROM sys_role_menu;
--;;
DELETE FROM sys_user_post;
--;;
DELETE FROM sys_online;
--;;
DELETE FROM sys_job_log;
--;;
DELETE FROM sys_job;
--;;
DELETE FROM sys_login_log;
--;;
DELETE FROM sys_oper_log;
--;;
DELETE FROM sys_config;
--;;
DELETE FROM sys_dict_data;
--;;
DELETE FROM sys_dict_type;
--;;
DELETE FROM sys_user;
--;;
DELETE FROM sys_post;
--;;
DELETE FROM sys_role;
--;;
DELETE FROM sys_menu;
--;;
DELETE FROM sys_dept;
