CREATE TABLE sys_post (
  post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_code VARCHAR(64) NOT NULL,
  post_name VARCHAR(50) NOT NULL,
  post_sort INT DEFAULT 0,
  status CHAR(1) DEFAULT '0',
  create_by VARCHAR(64) DEFAULT '',
  create_time TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
  update_by VARCHAR(64) DEFAULT '',
  update_time TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')),
  remark VARCHAR(500) DEFAULT ''
);
--;;
CREATE INDEX idx_sys_post_status ON sys_post(status);
